from typing import Any, Union

class V2f:
    def __init__(self, x: float, y: float) -> None: ...
    def setValue(self, x: float, y: float) -> None: ...
    x: float
    y: float

class Box3d: ...

class _BaseArray:
    def __init__(self, length: int) -> None: ...
    def __setitem__(self, index: Union[int, slice], value: Any) -> None: ...
    def __getitem__(self, index: Union[int, slice]) -> Any: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Any: ...

class FloatArray(_BaseArray): ...
class IntArray(_BaseArray): ...
class UnsignedIntArray(_BaseArray): ...

class V2fArray(_BaseArray):
    x: FloatArray
    y: FloatArray

class V3fArray(_BaseArray):
    x: FloatArray
    y: FloatArray
    z: FloatArray
