from typing import Any
from imath import Box3d, V3fArray, IntArray, V2fArray, UnsignedIntArray

class IObject:
    children: list['IObject']
    def getName(self) -> str: ...
    def getParent(self) -> IObject: ...
    def getMetaData(self) -> Any: ...
    def getProperties(self) -> ICompoundProperty: ...
    def getNumChildren(self) -> int: ...
    def getChild(self, index: int) -> IObject: ...

class OObject:
    def __init__(self, parent: OObject, name: str, metaData: Any = None) -> None: ...
    def getProperties(self) -> OCompoundProperty: ...

class IArchive:
    def __init__(self, path: str | list[str]) -> None: ...
    def getTop(self) -> IObject: ...
    def getNumTimeSamplings(self) -> int: ...
    def getTimeSampling(self, idx: int) -> Any: ...

class OArchive:
    def __init__(self, path: str, ogawa: bool = ...) -> None: ...
    def getTop(self) -> OObject: ...
    def addTimeSampling(self, ts: Any) -> None: ...

class OProperty:
    def setTimeSampling(self, timeSampling: Any) -> None: ...
    def setValue(self, value: Any) -> None: ...

class IProperty:
    def getName(self) -> str: ...
    def getValue(self) -> Any: ...
    def getDataType(self) -> Any: ...
    def isCompound(self) -> bool: ...
    def isArray(self) -> bool: ...
    def getMetaData(self) -> Any: ...
    def getTimeSampling(self) -> Any: ...
    samples: list[Any]

class ICompoundProperty(IProperty):
    def valid(self) -> bool: ...
    def getProperty(self, str) -> IProperty: ...
    def getNumProperties(self) -> int: ...

class OCompoundProperty(OProperty):
    def __init__(
        self, parent: OCompoundProperty, name: str, metaData: Any = None
    ) -> None: ...

class OStringProperty(OProperty):
    def __init__(self, props: OCompoundProperty, key: str) -> None: ...
    def setValue(self, value: str) -> None: ...

class OScalarProperty(OProperty):
    def __init__(
        self,
        parent: OCompoundProperty,
        name: str,
        dataType: Any = None,
        metaData: Any = None,
    ) -> None: ...

class OArrayProperty(OProperty):
    def __init__(
        self,
        parent: OCompoundProperty,
        name: str,
        dataType: Any = None,
        metaData: Any = None,
    ) -> None: ...

class OBox3dProperty(OProperty):
    def setValue(self, value: Box3d) -> None: ...

class IP3fArrayProperty(IProperty):
    samples: list[V3fArray]

class IInt32ArrayProperty(IProperty):
    samples: list[IntArray]

class IV2fArrayProperty(IProperty):
    def getValue(self) -> V2fArray: ...

class IUInt32ArrayProperty(IProperty):
    def getValue(self) -> UnsignedIntArray: ...

class IV2fGeomParam:
    def valid(self) -> bool: ...
    def isIndexed(self) -> bool: ...
    def getValueProperty(self) -> IV2fArrayProperty: ...
    def getIndexProperty(self) -> IUInt32ArrayProperty: ...
