from typing import Any, List
from imath import Box3d, V3fArray, IntArray, V2fArray, UnsignedIntArray

class IObject:
    children: List['IObject']
    def getName(self) -> str: ...
    def getParent(self) -> 'IObject': ...
    def getMetaData(self) -> Any: ...

class OObject:
    pass

class IArchive:
    def __init__(self, path: str) -> None: ...
    def getTop(self) -> IObject: ...

class OArchive:
    def __init__(self, path: str, ogawa: bool = ...) -> None: ...
    def getTop(self) -> OObject: ...

class IProperty:
    def getValue(self) -> Any: ...

class ICompoundProperty:
    def valid(self) -> bool: ...
    def getProperty(self, str) -> IProperty: ...

class OCompoundProperty: ...

class OStringProperty:
    def __init__(self, props: OCompoundProperty, key: str) -> None: ...
    def setValue(self, value: str) -> None: ...

class OBox3dProperty:
    def setValue(self, value: Box3d) -> None: ...

class IP3fArrayProperty:
    samples: list[V3fArray]

class IInt32ArrayProperty:
    samples: list[IntArray]

class IV2fArrayProperty:
    def getValue(self) -> V2fArray: ...

class IUInt32ArrayProperty:
    def getValue(self) -> UnsignedIntArray: ...

class IV2fGeomParam:
    def valid(self) -> bool: ...
    def isIndexed(self) -> bool: ...
    def getValueProperty(self) -> IV2fArrayProperty: ...
    def getIndexProperty(self) -> IUInt32ArrayProperty: ...
