from typing import Any
from alembic.Abc import (
    IObject,
    OObject,
    OBox3dProperty,
    IP3fArrayProperty,
    IInt32ArrayProperty,
    IV2fGeomParam,
)
from alembic.AbcCoreAbstract import MetaData

class GeometryScope:
    kFacevaryingScope: Any

class ON3fGeomParamSample:
    def __init__(self, array: Any, indexes_or_scope: Any, scope: Any = ...) -> None: ...

class OV2fGeomParamSample:
    def __init__(self, array: Any, indexes_or_scope: Any, scope: Any = ...) -> None: ...

class OPolyMeshSchema:
    def getChildBoundsProperty(self) -> OBox3dProperty: ...
    def set(self, sample: OPolyMeshSchemaSample) -> None: ...

class IPolyMeshSchema:
    def getPositionsProperty(self) -> IP3fArrayProperty: ...
    def getFaceIndicesProperty(self) -> IInt32ArrayProperty: ...
    def getFaceCountsProperty(self) -> IInt32ArrayProperty: ...
    def getUVsParam(self) -> IV2fGeomParam: ...

class IPolyMesh(_IBase):
    def getSchema(self) -> IPolyMeshSchema: ...

class OPolyMeshSchemaSample:
    def __init__(
        self, points: Any, faceIndex: Any, faceCount: Any, **kwargs
    ) -> None: ...

class _IBase(IObject):
    def __init__(self, parent: IObject, name: str) -> None: ...
    @classmethod
    def matches(cls, md: MetaData) -> bool: ...
    def getSchema(self) -> Any: ...

class ICamera(_IBase): ...
class ICurves(_IBase): ...
class ILight(_IBase): ...
class INuPatch(_IBase): ...
class IPoints(_IBase): ...
class ISubD(_IBase): ...
class IXform(_IBase): ...

class _OBase(OObject):
    def __init__(self, parent: OObject, name: str) -> None: ...
    def getSchema(self) -> Any: ...

class OPolyMesh(_OBase): ...
class OXform(_OBase): ...
