option(
  'maya_version',
  type : 'string',
  value : '2024',
  description : 'The version of Maya to compile for',
  yield : true,
)

option(
  'maya_devkit_base',
  type : 'string',
  value : '',
  description : 'Optional path to the maya devkit',
  yield : true,
)

option(
  'maya_custom_install_path',
  type : 'string',
  value : '',
  description : 'Path to a non-standard maya install',
  yield : true,
)

option(
  'maya_qt_extra_includes',
  type : 'string',
  value : '',
  description : 'Any qt headers other than QtCore, QtGui, or QtWidgets that you need to include, separated by semicolons',
  yield : true,
)

option(
  'maya_link_qt',
  type : 'feature',
  value : 'auto',
  description : 'Provide maya-qt dependency linking to Maya\'s Qt libraries',
  yield : true,
)

option(
  'maya_link_opengl',
  type : 'feature',
  value : 'auto',
  description : 'Provide maya-opengl dependency linking to opengl and glu',
  yield : true,
)

option(
  'maya_link_numpy',
  type : 'feature',
  value : 'disabled',
  description : 'Provide maya-numpy dependency (Requires maya_install_path to exist)',
  yield : true,
)

option(
  'maya_link_alembic',
  type : 'feature',
  value : 'auto',
  description : 'Provide maya-alembic dependency (Requires maya_devkit_base)',
  yield : true,
)

option(
  'maya_link_imath',
  type : 'feature',
  value : 'auto',
  description : 'Provide maya-imath dependency (Requires maya_devkit_base)',
  yield : true,
)

option(
  'maya_link_ufe',
  type : 'feature',
  value : 'auto',
  description : 'Provide maya-ufe dependency (Requires maya_devkit_base)',
  yield : true,
)
