from loadUiType import Qt

PRECISION = 4
COLUMNCOUNT = 3

THING_ROLE = Qt.UserRole + 1
VALUE_ROLE = Qt.UserRole + 2
WEIGHT_ROLE = Qt.UserRole + 3
TYPE_ROLE = Qt.UserRole + 4
PARENT_ROLE = Qt.UserRole + 5

THING_NAME_COL = 0
SLIDER_VALUE_COL = 1
SHAPE_WEIGHT_COL = 2

S_SHAPE_TYPE = 10
S_SLIDER_TYPE = 9
S_GROUP_TYPE = 8
S_SYSTEM_TYPE = 7

C_SHAPE_TYPE = 6
C_SHAPE_PAR_TYPE = 5
C_SLIDER_TYPE = 4
C_SLIDER_PAR_TYPE = 3
C_COMBO_TYPE = 2
C_GROUP_TYPE = 1
C_SYSTEM_TYPE = 0

